### ISSUE TITLE
启用后左侧菜单无Blockly页面

### ISSUE THREAD

**Issue by Fox-ace** [koishijs/koishi-plugin-blockly#63]
LinuxManjaro , 安装插件启用后日志出现报错
`运行日志

2024-08-25 14:14:13 [W] app Error: property blockly is not registered, declare it as `inject` to suppress this warning at BlocklyVendorDataService.get (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/koishi-plugin-blockly/lib/vendor.js:10:25) at /home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:56:25 at Object.apply (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@cordisjs/core/lib/index.cjs:171:28) at /home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:258:27 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Promise.all (index 0) at async Proxy.broadcast (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:253:5)

2024-08-25 14:14:13 [W] app Error: property blockly is not registered, declare it as `inject` to suppress this warning at BlocklyVendorDataService.get (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/koishi-plugin-blockly/lib/vendor.js:10:25) at /home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:56:25 at Object.apply (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@cordisjs/core/lib/index.cjs:171:28) at /home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:258:27 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Promise.all (index 1) at async Proxy.broadcast (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/@koishijs/plugin-console/node_modules/@koishijs/console/lib/index.js:253:5)

2024-08-25 14:14:13 [W] app Error: property router is not registered, declare it as `inject` to suppress this warning at registerStaticFileRoute (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/koishi-plugin-blockly/lib/static.js:10:9) at Object.apply (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/koishi-plugin-blockly/lib/index.js:41:42) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

2024-08-25 14:14:13 [E] app TypeError: Cannot read properties of undefined (reading 'get') at registerStaticFileRoute (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/koishi-plugin-blockly/lib/static.js:10:16) at Object.apply (/home/fox/Develop/koishi-desktop-linux-x64-v1.1.3/data/instances/default/node_modules/koishi-plugin-blockly/lib/index.js:41:42) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by Fox-ace** [comment]
![1000402863](https://github.com/user-attachments/assets/4f2f5b8b-5b2f-4783-b1ae-edd67a8d5996)
![1000402862](https://github.com/user-attachments/assets/738762a4-d5e4-418d-9dca-3e895063a9cf)
